# Generated by Django 4.0.1 on 2022-06-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='parroquia')),
                ('tipo_parroquia', models.CharField(choices=[('urbana', 'Parroquia Urbana'), ('rural', 'Parroquia Rural')], max_length=30, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='barrio')),
                ('num_viviendas', models.IntegerField(verbose_name='numero de viviendas')),
                ('parques', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=30, verbose_name='numero de parques')),
                ('num_edificios', models.IntegerField(verbose_name='numero de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
        ),
    ]
